/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 29
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 28
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_playlist_token1 = 1,
  sym_header = 2,
  anon_sym_POUNDEXTINF = 3,
  anon_sym_COLON = 4,
  anon_sym_COMMA = 5,
  sym_duration = 6,
  aux_sym_title_token1 = 7,
  sym_tag_name = 8,
  aux_sym_tag_content_token1 = 9,
  anon_sym_EQ = 10,
  sym_tag_word = 11,
  sym_unquoted_value = 12,
  sym_quoted_string = 13,
  sym_comment = 14,
  aux_sym_uri_token1 = 15,
  sym_variable = 16,
  sym_playlist = 17,
  sym_extinf = 18,
  sym_title = 19,
  sym_tag = 20,
  sym_tag_content = 21,
  sym_attribute = 22,
  sym_uri = 23,
  aux_sym_playlist_repeat1 = 24,
  aux_sym_extinf_repeat1 = 25,
  aux_sym_title_repeat1 = 26,
  aux_sym_tag_content_repeat1 = 27,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_playlist_token1] = "playlist_token1",
  [sym_header] = "header",
  [anon_sym_POUNDEXTINF] = "#EXTINF",
  [anon_sym_COLON] = ":",
  [anon_sym_COMMA] = ",",
  [sym_duration] = "duration",
  [aux_sym_title_token1] = "title_token1",
  [sym_tag_name] = "tag_name",
  [aux_sym_tag_content_token1] = "tag_content_token1",
  [anon_sym_EQ] = "=",
  [sym_tag_word] = "tag_word",
  [sym_unquoted_value] = "unquoted_value",
  [sym_quoted_string] = "quoted_string",
  [sym_comment] = "comment",
  [aux_sym_uri_token1] = "uri_token1",
  [sym_variable] = "variable",
  [sym_playlist] = "playlist",
  [sym_extinf] = "extinf",
  [sym_title] = "title",
  [sym_tag] = "tag",
  [sym_tag_content] = "tag_content",
  [sym_attribute] = "attribute",
  [sym_uri] = "uri",
  [aux_sym_playlist_repeat1] = "playlist_repeat1",
  [aux_sym_extinf_repeat1] = "extinf_repeat1",
  [aux_sym_title_repeat1] = "title_repeat1",
  [aux_sym_tag_content_repeat1] = "tag_content_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_playlist_token1] = aux_sym_playlist_token1,
  [sym_header] = sym_header,
  [anon_sym_POUNDEXTINF] = anon_sym_POUNDEXTINF,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_duration] = sym_duration,
  [aux_sym_title_token1] = aux_sym_title_token1,
  [sym_tag_name] = sym_tag_name,
  [aux_sym_tag_content_token1] = aux_sym_tag_content_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_tag_word] = sym_tag_word,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_quoted_string] = sym_quoted_string,
  [sym_comment] = sym_comment,
  [aux_sym_uri_token1] = aux_sym_uri_token1,
  [sym_variable] = sym_variable,
  [sym_playlist] = sym_playlist,
  [sym_extinf] = sym_extinf,
  [sym_title] = sym_title,
  [sym_tag] = sym_tag,
  [sym_tag_content] = sym_tag_content,
  [sym_attribute] = sym_attribute,
  [sym_uri] = sym_uri,
  [aux_sym_playlist_repeat1] = aux_sym_playlist_repeat1,
  [aux_sym_extinf_repeat1] = aux_sym_extinf_repeat1,
  [aux_sym_title_repeat1] = aux_sym_title_repeat1,
  [aux_sym_tag_content_repeat1] = aux_sym_tag_content_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_playlist_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_header] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUNDEXTINF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_duration] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_title_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_tag_content_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_tag_word] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_uri_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_playlist] = {
    .visible = true,
    .named = true,
  },
  [sym_extinf] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_content] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_uri] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_playlist_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_extinf_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_title_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_content_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_duration = 1,
  field_name = 2,
  field_title = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_duration] = "duration",
  [field_name] = "name",
  [field_title] = "title",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_duration, 2},
  [1] =
    {field_duration, 2},
    {field_title, 4},
  [3] =
    {field_name, 0},
    {field_value, 2},
  [5] =
    {field_duration, 2},
    {field_title, 5},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 9,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 25,
  [27] = 27,
  [28] = 28,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(17);
      ADVANCE_MAP(
        '\n', 18,
        '\r', 1,
        '"', 104,
        '#', 83,
        ',', 22,
        ':', 21,
        '=', 51,
        '{', 47,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(103);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(18);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(79);
      END_STATE();
    case 4:
      if (lookahead == '$') ADVANCE(6);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(5);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 6:
      if (lookahead == '}') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(6);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 10:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(104);
      if (lookahead == '#') ADVANCE(56);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(78);
      END_STATE();
    case 11:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(104);
      if (lookahead == '#') ADVANCE(56);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '=') ADVANCE(103);
      if (lookahead == '{') ADVANCE(52);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(78);
      END_STATE();
    case 12:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '"') ADVANCE(103);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '=') ADVANCE(51);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(78);
      END_STATE();
    case 13:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(84);
      if (lookahead == ':') ADVANCE(21);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(103);
      END_STATE();
    case 14:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(84);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(103);
      END_STATE();
    case 15:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '#') ADVANCE(57);
      if (lookahead == ',') ADVANCE(22);
      if (lookahead == '{') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(15);
      if (lookahead == '"' ||
          lookahead == '=') ADVANCE(103);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(78);
      END_STATE();
    case 16:
      if (eof) ADVANCE(17);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(38);
      if (lookahead != 0) ADVANCE(38);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_playlist_token1);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_header);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_POUNDEXTINF);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_duration);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_duration);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\n') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(38);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '\r') ADVANCE(25);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      if (lookahead == 0x0b ||
          lookahead == '\f') ADVANCE(38);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(38);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'A') ADVANCE(36);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'E') ADVANCE(35);
      if (lookahead == 'P') ADVANCE(30);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'I') ADVANCE(32);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'L') ADVANCE(27);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'L') ADVANCE(29);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'S') ADVANCE(34);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'X') ADVANCE(33);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == 'Y') ADVANCE(31);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead == '{') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_title_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '{') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_tag_name);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '3') ADVANCE(44);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'F') ADVANCE(20);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'I') ADVANCE(43);
      if (lookahead == 'M') ADVANCE(40);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'N') ADVANCE(41);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == 'U') ADVANCE(19);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '$') ADVANCE(48);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(50);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '}') ADVANCE(105);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_tag_content_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ') ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '$') ADVANCE(74);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(78);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '$') ADVANCE(75);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(78);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'A') ADVANCE(72);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'A') ADVANCE(73);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'E') ADVANCE(70);
      if (lookahead == 'P') ADVANCE(60);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'E') ADVANCE(71);
      if (lookahead == 'P') ADVANCE(62);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'I') ADVANCE(64);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'I') ADVANCE(65);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'L') ADVANCE(54);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'L') ADVANCE(58);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'L') ADVANCE(55);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'L') ADVANCE(59);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'S') ADVANCE(68);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'S') ADVANCE(69);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'X') ADVANCE(66);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'X') ADVANCE(67);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'Y') ADVANCE(61);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == 'Y') ADVANCE(63);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '}') ADVANCE(105);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(48);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '}') ADVANCE(105);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(6);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(101);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ' ||
          lookahead == '"' ||
          lookahead == ',' ||
          lookahead == '=') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_tag_word);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ',' &&
          lookahead != '=') ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != ',') ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'A') ADVANCE(99);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'A') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'E') ADVANCE(97);
      if (lookahead == 'P') ADVANCE(87);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'E') ADVANCE(98);
      if (lookahead == 'P') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'I') ADVANCE(91);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'I') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'L') ADVANCE(81);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'L') ADVANCE(85);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'L') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'L') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'S') ADVANCE(95);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'S') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'T') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'T') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'X') ADVANCE(93);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'X') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'Y') ADVANCE(88);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == 'Y') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_uri_token1);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_uri_token1);
      if (lookahead == '"') ADVANCE(80);
      if (lookahead == '\\') ADVANCE(49);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(46);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_variable);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 15},
  [7] = {.lex_state = 14},
  [8] = {.lex_state = 14},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 15},
  [11] = {.lex_state = 15},
  [12] = {.lex_state = 16},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 16},
  [15] = {.lex_state = 16},
  [16] = {.lex_state = 16},
  [17] = {.lex_state = 16},
  [18] = {.lex_state = 16},
  [19] = {.lex_state = 15},
  [20] = {.lex_state = 13},
  [21] = {.lex_state = 13},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 3},
  [26] = {.lex_state = 3},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_playlist_token1] = ACTIONS(1),
    [sym_header] = ACTIONS(1),
    [anon_sym_POUNDEXTINF] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [aux_sym_tag_content_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_uri_token1] = ACTIONS(1),
    [sym_variable] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_playlist] = STATE(28),
    [sym_extinf] = STATE(7),
    [sym_tag] = STATE(7),
    [sym_uri] = STATE(7),
    [aux_sym_playlist_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_playlist_token1] = ACTIONS(5),
    [sym_header] = ACTIONS(5),
    [anon_sym_POUNDEXTINF] = ACTIONS(7),
    [sym_tag_name] = ACTIONS(9),
    [sym_comment] = ACTIONS(11),
    [aux_sym_uri_token1] = ACTIONS(13),
    [sym_variable] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_tag_content] = STATE(22),
    [sym_attribute] = STATE(3),
    [aux_sym_tag_content_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(15),
    [aux_sym_playlist_token1] = ACTIONS(15),
    [sym_header] = ACTIONS(15),
    [anon_sym_POUNDEXTINF] = ACTIONS(15),
    [anon_sym_COMMA] = ACTIONS(17),
    [sym_tag_name] = ACTIONS(19),
    [aux_sym_tag_content_token1] = ACTIONS(21),
    [sym_tag_word] = ACTIONS(23),
    [sym_quoted_string] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
    [aux_sym_uri_token1] = ACTIONS(19),
    [sym_variable] = ACTIONS(15),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(23), 1,
      sym_tag_word,
    ACTIONS(31), 1,
      aux_sym_tag_content_token1,
    ACTIONS(27), 2,
      anon_sym_COMMA,
      sym_quoted_string,
    STATE(4), 2,
      sym_attribute,
      aux_sym_tag_content_repeat1,
    ACTIONS(29), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(25), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [27] = 6,
    ACTIONS(40), 1,
      aux_sym_tag_content_token1,
    ACTIONS(43), 1,
      sym_tag_word,
    ACTIONS(35), 2,
      anon_sym_COMMA,
      sym_quoted_string,
    STATE(4), 2,
      sym_attribute,
      aux_sym_tag_content_repeat1,
    ACTIONS(38), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(33), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [54] = 3,
    ACTIONS(50), 1,
      anon_sym_EQ,
    ACTIONS(48), 5,
      sym_tag_name,
      aux_sym_tag_content_token1,
      sym_tag_word,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(46), 7,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      anon_sym_COMMA,
      sym_quoted_string,
      sym_variable,
  [74] = 5,
    ACTIONS(54), 1,
      anon_sym_COMMA,
    ACTIONS(58), 1,
      sym_tag_word,
    STATE(11), 2,
      sym_attribute,
      aux_sym_extinf_repeat1,
    ACTIONS(56), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(52), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [97] = 7,
    ACTIONS(7), 1,
      anon_sym_POUNDEXTINF,
    ACTIONS(9), 1,
      sym_tag_name,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      sym_comment,
    ACTIONS(13), 2,
      aux_sym_uri_token1,
      sym_variable,
    ACTIONS(62), 2,
      aux_sym_playlist_token1,
      sym_header,
    STATE(8), 4,
      sym_extinf,
      sym_tag,
      sym_uri,
      aux_sym_playlist_repeat1,
  [124] = 7,
    ACTIONS(66), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_POUNDEXTINF,
    ACTIONS(74), 1,
      sym_tag_name,
    ACTIONS(77), 1,
      sym_comment,
    ACTIONS(68), 2,
      aux_sym_playlist_token1,
      sym_header,
    ACTIONS(80), 2,
      aux_sym_uri_token1,
      sym_variable,
    STATE(8), 4,
      sym_extinf,
      sym_tag,
      sym_uri,
      aux_sym_playlist_repeat1,
  [151] = 2,
    ACTIONS(85), 5,
      sym_tag_name,
      aux_sym_tag_content_token1,
      sym_tag_word,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(83), 7,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      anon_sym_COMMA,
      sym_quoted_string,
      sym_variable,
  [168] = 4,
    ACTIONS(91), 1,
      sym_tag_word,
    STATE(10), 2,
      sym_attribute,
      aux_sym_extinf_repeat1,
    ACTIONS(89), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(87), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      anon_sym_COMMA,
      sym_variable,
  [189] = 5,
    ACTIONS(58), 1,
      sym_tag_word,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(10), 2,
      sym_attribute,
      aux_sym_extinf_repeat1,
    ACTIONS(98), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(94), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [212] = 5,
    ACTIONS(94), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_title_repeat1,
    STATE(23), 1,
      sym_title,
    ACTIONS(100), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(98), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [234] = 3,
    ACTIONS(106), 1,
      anon_sym_EQ,
    ACTIONS(104), 4,
      sym_tag_name,
      sym_tag_word,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(102), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      anon_sym_COMMA,
      sym_variable,
  [252] = 5,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      aux_sym_title_repeat1,
    STATE(24), 1,
      sym_title,
    ACTIONS(100), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(110), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [274] = 4,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_title_repeat1,
    ACTIONS(116), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(114), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [293] = 4,
    ACTIONS(118), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_title_repeat1,
    ACTIONS(122), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(120), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [312] = 4,
    ACTIONS(124), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_title_repeat1,
    ACTIONS(116), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(126), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [331] = 4,
    ACTIONS(128), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      aux_sym_title_repeat1,
    ACTIONS(132), 2,
      aux_sym_title_token1,
      sym_variable,
    ACTIONS(130), 6,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
  [350] = 2,
    ACTIONS(85), 4,
      sym_tag_name,
      sym_tag_word,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(83), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      anon_sym_COMMA,
      sym_variable,
  [365] = 3,
    ACTIONS(137), 1,
      anon_sym_COLON,
    ACTIONS(139), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [381] = 3,
    ACTIONS(143), 1,
      anon_sym_COLON,
    ACTIONS(145), 3,
      sym_tag_name,
      sym_comment,
      aux_sym_uri_token1,
    ACTIONS(141), 5,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      sym_variable,
  [397] = 2,
    ACTIONS(149), 2,
      sym_tag_name,
      sym_comment,
    ACTIONS(147), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      aux_sym_uri_token1,
      sym_variable,
  [410] = 2,
    ACTIONS(153), 2,
      sym_tag_name,
      sym_comment,
    ACTIONS(151), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      aux_sym_uri_token1,
      sym_variable,
  [423] = 2,
    ACTIONS(157), 2,
      sym_tag_name,
      sym_comment,
    ACTIONS(155), 6,
      ts_builtin_sym_end,
      aux_sym_playlist_token1,
      sym_header,
      anon_sym_POUNDEXTINF,
      aux_sym_uri_token1,
      sym_variable,
  [436] = 1,
    ACTIONS(159), 2,
      sym_unquoted_value,
      sym_quoted_string,
  [441] = 1,
    ACTIONS(161), 2,
      sym_unquoted_value,
      sym_quoted_string,
  [446] = 1,
    ACTIONS(163), 1,
      sym_duration,
  [450] = 1,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 27,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 74,
  [SMALL_STATE(7)] = 97,
  [SMALL_STATE(8)] = 124,
  [SMALL_STATE(9)] = 151,
  [SMALL_STATE(10)] = 168,
  [SMALL_STATE(11)] = 189,
  [SMALL_STATE(12)] = 212,
  [SMALL_STATE(13)] = 234,
  [SMALL_STATE(14)] = 252,
  [SMALL_STATE(15)] = 274,
  [SMALL_STATE(16)] = 293,
  [SMALL_STATE(17)] = 312,
  [SMALL_STATE(18)] = 331,
  [SMALL_STATE(19)] = 350,
  [SMALL_STATE(20)] = 365,
  [SMALL_STATE(21)] = 381,
  [SMALL_STATE(22)] = 397,
  [SMALL_STATE(23)] = 410,
  [SMALL_STATE(24)] = 423,
  [SMALL_STATE(25)] = 436,
  [SMALL_STATE(26)] = 441,
  [SMALL_STATE(27)] = 446,
  [SMALL_STATE(28)] = 450,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_playlist, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_content, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_content, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [38] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_content_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_content_repeat1, 1, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_content_repeat1, 1, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 3, 0, 1),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 3, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_playlist, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [74] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [77] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_playlist_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 2, 3),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 2, 3),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extinf_repeat1, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_extinf_repeat1, 2, 0, 0),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_extinf_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 4, 0, 1),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 4, 0, 1),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_extinf_repeat1, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_extinf_repeat1, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 5, 0, 1),
  [110] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 5, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uri, 2, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uri, 2, 0, 0),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_uri, 1, 0, 0),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_uri, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_title, 1, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_title_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 5, 0, 2),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 5, 0, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extinf, 6, 0, 4),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extinf, 6, 0, 4),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [165] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_m3u(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "m3u",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
